[package]
name = "combustion-cli"
version = "0.1.0"
authors = ["Layl <LaylConway@users.noreply.github.com>"]

[dependencies]
clap = "2.17.1"
slog = "1.3.0"
slog-term = "1.3.3"
combustion = { path = "../" }
